### ISSUE TITLE
Re-render pagination buttons

### ISSUE THREAD

**Issue by ravencedrick** [josecebe/twbs-pagination#187]
Hi. I want to know if there is a re-render of the page button list? Because I did some filter search on an api. So when I request and get paging response I want to change the count of buttons. Is it possible?

**Comment by Trzinka** [comment]
Hi. 

Try this : 

https://codepen.io/robert-peri/pen/zyPpyX?editors=1010 


Od: "Raven Cedrick Cabrera" <notifications@github.com> 
Za: "josecebe/twbs-pagination" <twbs-pagination@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Poslano: Torek, 15. Januar 2019 10:33:51 
Zadeva: [josecebe/twbs-pagination] Re-render pagination buttons (#187) 



Hi. I want to know if there is a re-render of the page button list? Because I did some filter search on an api. So when I request and get paging response I want to change the count of buttons. Is it possible?

**Comment by josecebe** [comment]
This issue was resolved: https://github.com/josecebe/twbs-pagination/issues/172

You can re-render the pagination buttons using "changeTotalPages" method.

In the issue I've mentioned above you can see further information.

@Trzinka you can suggest improvements over this plugin (and provide those improvements in a Pull Request), but I don't think it's a correct behaviour from you the fact of suggest the use of other plugins in this page (I mean other pagination plugins). Especially if the issue is completly resolved on twbsPagination.

**Comment by Trzinka** [comment]
Hi. I'm sorry. 

My purpose was to simply solve the problem that I encountered when using twbs-pagination. 

I think that there are quite a few suggestions for improving the twbs-pagination that I agreed with. 

I'm sorry again in the future I will no longer be answering questions related to twbs-pagination. 

Get a nice greeting from Slovenia and continue with good work. 
Robert. 


Od: "Jose Cebellán" <notifications@github.com> 
Za: "josecebe/twbs-pagination" <twbs-pagination@noreply.github.com> 
Cc: "Robert Perič" <trzinka@siol.net>, "Mention" <mention@noreply.github.com> 
Poslano: Sreda, 16. Januar 2019 11:36:48 
Zadeva: Re: [josecebe/twbs-pagination] Re-render pagination buttons (#187) 



This issue was resolved: #172 


You can re-render the pagination buttons using "changeTotalPages" method. 

In the issue I've mentioned above you can see further information. 

@Trzinka you can suggest improvements over this plugin (and provide those improvements in a Pull Request), but I don't think it's a correct behaviour from you the fact of suggest the use of other plugins in this page (I mean other pagination plugins). Especially if the issue is completly resolved on twbsPagination.
